-- MySQL Script generated by MySQL Workbench
-- Fri Apr  9 00:05:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gifty
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gifty
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gifty` DEFAULT CHARACTER SET utf8 ;
USE `gifty` ;

-- -----------------------------------------------------
-- Table `gifty`.`cadeaux`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gifty`.`cadeaux` ;

CREATE TABLE IF NOT EXISTS `gifty`.`cadeaux` (
  `idcadeaux` INT NOT NULL,
  `nom_cadeaux` VARCHAR(45) NULL,
  `hobby` VARCHAR(45) NULL,
  `prix` FLOAT NULL,
  `type_cadeau` VARCHAR(45) NULL,
  PRIMARY KEY (`idcadeaux`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifty`.`blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gifty`.`blog` ;

CREATE TABLE IF NOT EXISTS `gifty`.`blog` (
  `idblog` INT NOT NULL,
  `titre` VARCHAR(45) NULL,
  `description` NVARCHAR(300) NOT NULL,
  PRIMARY KEY (`idblog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifty`.`compte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gifty`.`compte` ;

CREATE TABLE IF NOT EXISTS `gifty`.`compte` (
  `idcompte` INT NOT NULL,
  `nom client` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `age` INT(3) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot de passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcompte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifty`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gifty`.`client` ;

CREATE TABLE IF NOT EXISTS `gifty`.`client` (
  `idclient` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `age` INT(3) NOT NULL,
  `compte_idcompte` INT NOT NULL,
  PRIMARY KEY (`idclient`, `compte_idcompte`),
  INDEX `fk_client_compte1_idx` (`compte_idcompte` ASC) VISIBLE,
  CONSTRAINT `fk_client_compte1`
    FOREIGN KEY (`compte_idcompte`)
    REFERENCES `gifty`.`compte` (`idcompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifty`.`profil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gifty`.`profil` ;

CREATE TABLE IF NOT EXISTS `gifty`.`profil` (
  `idprofil` INT NOT NULL,
  `nom utilisateur` VARCHAR(45) NOT NULL,
  `mot de passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprofil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifty`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gifty`.`admin` ;

CREATE TABLE IF NOT EXISTS `gifty`.`admin` (
  `idadmin` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot de passe` VARCHAR(45) NOT NULL,
  `client_idclient` INT NOT NULL,
  `client_compte_idcompte` INT NOT NULL,
  `cadeaux_idcadeaux` INT NOT NULL,
  `blog_idblog` INT NOT NULL,
  `profil_idprofil` INT NOT NULL,
  PRIMARY KEY (`idadmin`, `client_idclient`, `client_compte_idcompte`, `cadeaux_idcadeaux`, `blog_idblog`, `profil_idprofil`),
  INDEX `fk_admin_client1_idx` (`client_idclient` ASC, `client_compte_idcompte` ASC) VISIBLE,
  INDEX `fk_admin_cadeaux1_idx` (`cadeaux_idcadeaux` ASC) VISIBLE,
  INDEX `fk_admin_blog1_idx` (`blog_idblog` ASC) VISIBLE,
  INDEX `fk_admin_profil1_idx` (`profil_idprofil` ASC) VISIBLE,
  CONSTRAINT `fk_admin_client1`
    FOREIGN KEY (`client_idclient` , `client_compte_idcompte`)
    REFERENCES `gifty`.`client` (`idclient` , `compte_idcompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_cadeaux1`
    FOREIGN KEY (`cadeaux_idcadeaux`)
    REFERENCES `gifty`.`cadeaux` (`idcadeaux`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_blog1`
    FOREIGN KEY (`blog_idblog`)
    REFERENCES `gifty`.`blog` (`idblog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_profil1`
    FOREIGN KEY (`profil_idprofil`)
    REFERENCES `gifty`.`profil` (`idprofil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifty`.`panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gifty`.`panier` ;

CREATE TABLE IF NOT EXISTS `gifty`.`panier` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifty`.`paiement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gifty`.`paiement` ;

CREATE TABLE IF NOT EXISTS `gifty`.`paiement` (
  `idpaiement` INT NOT NULL,
  `cadeaux_idcadeaux` INT NOT NULL,
  `panier_id` INT NOT NULL,
  PRIMARY KEY (`idpaiement`, `cadeaux_idcadeaux`, `panier_id`),
  INDEX `fk_paiement_cadeaux1_idx` (`cadeaux_idcadeaux` ASC) VISIBLE,
  INDEX `fk_paiement_panier1_idx` (`panier_id` ASC) VISIBLE,
  CONSTRAINT `fk_paiement_cadeaux1`
    FOREIGN KEY (`cadeaux_idcadeaux`)
    REFERENCES `gifty`.`cadeaux` (`idcadeaux`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paiement_panier1`
    FOREIGN KEY (`panier_id`)
    REFERENCES `gifty`.`panier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gifty`.`consulter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gifty`.`consulter` ;

CREATE TABLE IF NOT EXISTS `gifty`.`consulter` (
  `client_idclient` INT NOT NULL,
  `client_compte_idcompte` INT NOT NULL,
  `blog_idblog` INT NOT NULL,
  PRIMARY KEY (`client_idclient`, `client_compte_idcompte`, `blog_idblog`),
  INDEX `fk_client_has_blog_blog1_idx` (`blog_idblog` ASC) VISIBLE,
  INDEX `fk_client_has_blog_client1_idx` (`client_idclient` ASC, `client_compte_idcompte` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_blog_client1`
    FOREIGN KEY (`client_idclient` , `client_compte_idcompte`)
    REFERENCES `gifty`.`client` (`idclient` , `compte_idcompte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_blog_blog1`
    FOREIGN KEY (`blog_idblog`)
    REFERENCES `gifty`.`blog` (`idblog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
